name: controle_de_pagamentos
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: ^0.10.0

  cupertino_icons: ^1.0.2
  mobx: ^2.1.1
  path: ^1.8.2
  sqflite: ^2.1.0+1
  url_launcher: ^6.1.6

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/imgs/logo_escola.png'
  android: true

flutter_icons:
  image_path: 'assets/imgs/logo_escola.png'
  android: 'launcher_icon'
  adaptative_icon_background: '#FFFFFF'
  adaptative_icon_foreground: 'assets/imgs/logo_escola.png'


dev_dependencies:
  build_runner: ^2.3.0
  mobx_codegen: ^2.0.7+3

  flutter_lints: ^2.0.1

flutter:


  uses-material-design: true


  assets:
  - assets/fonts/
  - assets/imgs/

  fonts:
  - family: Coming Soon
    fonts:
    - asset: assets/fonts/ComingSoon-Regular.ttf
      weight: 400